TEST_SRCS = $(wildcard test*.c)
TEST_OBJS = $(TEST_SRCS:.c=.o)
RUNNERS = $(TEST_SRCS:%.c=runner_%)
RUN_TARGETS = $(TEST_SRCS:%.c=run_%)

.PHONY: test clean FORCE

test: $(RUN_TARGETS)
	@echo "All tests completed in $(DIR)."

run_%: runner_%
	@echo "running $< $(DIR)"
	@./$<

runner_%: %.o $(DBG_FULL_FILE)
	@echo "building test $@ $(DIR)"
	@gcc -o $@ $^ $(FLAGS) $(FLAGS_DBG) $(FLAGS_EXE)

%.o: %.c
	@echo "building test object $@ $(DIR)"
	@gcc -o $@ $< $(FLAGS) $(FLAGS_DBG) $(FLAGS_CMP)

clean:
	rm -rf $(TEST_OBJS) $(RUNNERS)